server:
  port: 8081
spring:
  application:
    name: "nutritional-plan"
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_workout
    username: postgres
    password: ""
    driverClassName: org.postgresql.Driver
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
